---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - acclr.github.com
  resources:
  - octnicupdaters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acclr.github.com
  resources:
  - octnicupdaters/finalizers
  verbs:
  - update
- apiGroups:
  - acclr.github.com
  resources:
  - octnicupdaters/status
  verbs:
  - get
  - patch
  - update
